"""
Enhanced Export System for NoteWise
Supports both text and PDF exports with professional formatting
"""

import os
import tempfile
from datetime import datetime
from typing import List, Dict, Any, Optional
from io import BytesIO

# PDF generation
try:
    from reportlab.lib.pagesizes import letter, A4
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib import colors
    from reportlab.lib.units import inch
    PDF_AVAILABLE = True
except ImportError:
    PDF_AVAILABLE = False

class EnhancedExporter:
    """
    Enhanced export system for NoteWise content
    Supports text and PDF exports with professional formatting
    """
    
    def __init__(self):
        self.styles = None
        if PDF_AVAILABLE:
            self._init_pdf_styles()
    
    def _init_pdf_styles(self):
        """Initialize PDF styles"""
        self.styles = getSampleStyleSheet()
        
        # Custom styles
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=18,
            textColor=colors.darkblue,
            spaceAfter=20,
            alignment=1  # Center alignment
        ))
        
        self.styles.add(ParagraphStyle(
            name='CustomHeading',
            parent=self.styles['Heading2'],
            fontSize=14,
            textColor=colors.darkgreen,
            spaceBefore=15,
            spaceAfter=10
        ))
        
        self.styles.add(ParagraphStyle(
            name='CustomBody',
            parent=self.styles['Normal'],
            fontSize=11,
            spaceAfter=10,
            leftIndent=20
        ))
        
        self.styles.add(ParagraphStyle(
            name='Question',
            parent=self.styles['Normal'],
            fontSize=12,
            textColor=colors.darkblue,
            spaceBefore=10,
            spaceAfter=5,
            leftIndent=10
        ))
        
        self.styles.add(ParagraphStyle(
            name='Answer',
            parent=self.styles['Normal'],
            fontSize=10,
            textColor=colors.darkred,
            spaceAfter=5,
            leftIndent=30
        ))
    
    def export_summary_text(self, summary: str, original_text: str = "", 
                           summary_type: str = "standard") -> str:
        """Export summary as formatted text"""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        text_content = f"""
# NoteWise Summary Export
Generated on: {timestamp}
Summary Type: {summary_type.title()}

## Original Text Summary
{summary}

---
Generated by NoteWise - Smart Study Assistant
        """.strip()
        
        if original_text:
            text_content += f"\n\n## Original Text (First 500 characters)\n{original_text[:500]}..."
        
        return text_content
    
    def export_summary_pdf(self, summary: str, original_text: str = "", 
                          summary_type: str = "standard") -> bytes:
        """Export summary as PDF"""
        if not PDF_AVAILABLE:
            raise ImportError("ReportLab not available for PDF export")
        
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=1*inch)
        story = []
        
        # Title
        title = Paragraph("📄 NoteWise Summary", self.styles['CustomTitle'])
        story.append(title)
        story.append(Spacer(1, 0.2*inch))
        
        # Metadata
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        meta_data = [
            ['Generated on:', timestamp],
            ['Summary Type:', summary_type.title()],
            ['Tool:', 'NoteWise - Smart Study Assistant']
        ]
        
        meta_table = Table(meta_data, colWidths=[2*inch, 4*inch])
        meta_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        
        story.append(meta_table)
        story.append(Spacer(1, 0.3*inch))
        
        # Summary content
        summary_heading = Paragraph("Summary", self.styles['CustomHeading'])
        story.append(summary_heading)
        
        # Split summary into paragraphs and add them
        summary_paragraphs = summary.split('\n')
        for para in summary_paragraphs:
            if para.strip():
                story.append(Paragraph(para.strip(), self.styles['CustomBody']))
        
        # Original text preview if provided
        if original_text:
            story.append(Spacer(1, 0.2*inch))
            original_heading = Paragraph("Original Text Preview", self.styles['CustomHeading'])
            story.append(original_heading)
            preview_text = original_text[:500] + "..." if len(original_text) > 500 else original_text
            story.append(Paragraph(preview_text, self.styles['CustomBody']))
        
        # Build PDF
        doc.build(story)
        pdf_data = buffer.getvalue()
        buffer.close()
        
        return pdf_data
    
    def export_questions_text(self, questions: List[Dict[str, Any]]) -> str:
        """Export questions as formatted text"""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        text_content = f"""
# NoteWise Questions Export
Generated on: {timestamp}
Total Questions: {len(questions)}

"""
        
        for i, question in enumerate(questions, 1):
            text_content += f"## Question {i}\n\n"
            text_content += f"**{question.get('question', 'No question text')}**\n\n"
            
            # Handle different question types
            if question.get('type') == 'Multiple Choice' and question.get('options'):
                text_content += "**Options:**\n"
                for j, opt in enumerate(question['options'], 1):
                    text_content += f"{j}. {opt}\n"
                text_content += f"\n**Answer:** {question.get('answer', 'No answer')}\n\n"
            elif question.get('type') == 'True/False':
                text_content += f"**Answer:** {question.get('answer', 'No answer')}\n\n"
            else:
                text_content += f"**Answer:** {question.get('answer', 'No answer')}\n\n"
            
            if question.get('explanation'):
                text_content += f"**Explanation:** {question['explanation']}\n\n"
            
            text_content += "---\n\n"
        
        text_content += "Generated by NoteWise - Smart Study Assistant"
        return text_content
    
    def export_questions_pdf(self, questions: List[Dict[str, Any]]) -> bytes:
        """Export questions as PDF"""
        if not PDF_AVAILABLE:
            raise ImportError("ReportLab not available for PDF export")
        
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=1*inch)
        story = []
        
        # Title
        title = Paragraph("❓ NoteWise Practice Questions", self.styles['CustomTitle'])
        story.append(title)
        story.append(Spacer(1, 0.2*inch))
        
        # Metadata
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        meta_data = [
            ['Generated on:', timestamp],
            ['Total Questions:', str(len(questions))],
            ['Tool:', 'NoteWise - Smart Study Assistant']
        ]
        
        meta_table = Table(meta_data, colWidths=[2*inch, 4*inch])
        meta_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        
        story.append(meta_table)
        story.append(Spacer(1, 0.3*inch))
        
        # Questions
        for i, question in enumerate(questions, 1):
            # Question number and text
            q_title = Paragraph(f"Question {i}", self.styles['CustomHeading'])
            story.append(q_title)
            
            q_text = Paragraph(question.get('question', 'No question text'), self.styles['Question'])
            story.append(q_text)
            
            # Options for MCQ
            if question.get('type') == 'Multiple Choice' and question.get('options'):
                for j, opt in enumerate(question['options'], 1):
                    option_text = Paragraph(f"{j}. {opt}", self.styles['CustomBody'])
                    story.append(option_text)
            
            # Answer
            answer_text = f"<b>Answer:</b> {question.get('answer', 'No answer')}"
            answer_para = Paragraph(answer_text, self.styles['Answer'])
            story.append(answer_para)
            
            # Explanation
            if question.get('explanation'):
                explanation_text = f"<b>Explanation:</b> {question['explanation']}"
                explanation_para = Paragraph(explanation_text, self.styles['Answer'])
                story.append(explanation_para)
            
            story.append(Spacer(1, 0.2*inch))
        
        # Build PDF
        doc.build(story)
        pdf_data = buffer.getvalue()
        buffer.close()
        
        return pdf_data
    
    def create_combined_export_pdf(self, summary: str, questions: List[Dict[str, Any]], 
                                  original_text: str = "", summary_type: str = "standard") -> bytes:
        """Create a combined PDF with both summary and questions"""
        if not PDF_AVAILABLE:
            raise ImportError("ReportLab not available for PDF export")
        
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=1*inch)
        story = []
        
        # Title
        title = Paragraph("📚 NoteWise Study Material", self.styles['CustomTitle'])
        story.append(title)
        story.append(Spacer(1, 0.2*inch))
        
        # Metadata
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        meta_data = [
            ['Generated on:', timestamp],
            ['Summary Type:', summary_type.title()],
            ['Questions:', str(len(questions))],
            ['Tool:', 'NoteWise - Smart Study Assistant']
        ]
        
        meta_table = Table(meta_data, colWidths=[2*inch, 4*inch])
        meta_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        
        story.append(meta_table)
        story.append(Spacer(1, 0.3*inch))
        
        # Summary section
        summary_heading = Paragraph("📄 Summary", self.styles['CustomHeading'])
        story.append(summary_heading)
        
        summary_paragraphs = summary.split('\n')
        for para in summary_paragraphs:
            if para.strip():
                story.append(Paragraph(para.strip(), self.styles['CustomBody']))
        
        story.append(Spacer(1, 0.3*inch))
        
        # Questions section
        questions_heading = Paragraph("❓ Practice Questions", self.styles['CustomHeading'])
        story.append(questions_heading)
        
        for i, question in enumerate(questions, 1):
            q_title = Paragraph(f"Question {i}", self.styles['CustomHeading'])
            story.append(q_title)
            
            q_text = Paragraph(question.get('question', 'No question text'), self.styles['Question'])
            story.append(q_text)
            
            if question.get('type') == 'Multiple Choice' and question.get('options'):
                for j, opt in enumerate(question['options'], 1):
                    option_text = Paragraph(f"{j}. {opt}", self.styles['CustomBody'])
                    story.append(option_text)
            
            answer_text = f"<b>Answer:</b> {question.get('answer', 'No answer')}"
            answer_para = Paragraph(answer_text, self.styles['Answer'])
            story.append(answer_para)
            
            if question.get('explanation'):
                explanation_text = f"<b>Explanation:</b> {question['explanation']}"
                explanation_para = Paragraph(explanation_text, self.styles['Answer'])
                story.append(explanation_para)
            
            story.append(Spacer(1, 0.15*inch))
        
        # Build PDF
        doc.build(story)
        pdf_data = buffer.getvalue()
        buffer.close()
        
        return pdf_data
